# Generated by Django 3.2.10 on 2022-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_no', models.CharField(max_length=50, verbose_name='缺陷编号')),
                ('bug_name', models.CharField(max_length=50, verbose_name='缺陷标题')),
                ('bug_desc', models.CharField(max_length=500, verbose_name='缺陷描述')),
                ('bug_state', models.CharField(choices=[('New', '新建'), ('Open', '打开'), ('Fixed', '已修复'), ('Closed', '已关闭')], default='New', max_length=10, verbose_name='缺陷编号')),
            ],
            options={
                'verbose_name': '缺陷报告',
                'verbose_name_plural': '缺陷报告',
            },
        ),
    ]
